// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqmlbwvzztmawyizockh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxbWxid3Z6enRtYXd5aXpvY2toIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyODE0ODEsImV4cCI6MjA2ODg1NzQ4MX0.L01zfaI-oIVEEYyDrsJNf57s_cIKSkHZz-zoTWTwYvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});