// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ziacaupojokswqmxpeew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppYWNhdXBvam9rc3dxbXhwZWV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MjE4NDIsImV4cCI6MjA2ODk5Nzg0Mn0.L4ex-bgrENhfVCq0XlvLL-__NVwZSt-Ny_S7KxewTiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});